#include "tesl_math.hpp"

#include "tesl_type.hpp"

namespace tesl {
  TESL_DEFINE_BUILTIN_TYPE_INFO_GETTER(Vec2, Vec2)
  TESL_DEFINE_BUILTIN_TYPE_INFO_GETTER(Vec3, Vec3)
  TESL_DEFINE_BUILTIN_TYPE_INFO_GETTER(Vec4, Vec4)
  TESL_DEFINE_BUILTIN_TYPE_INFO_GETTER(Mat2, Mat2)
  TESL_DEFINE_BUILTIN_TYPE_INFO_GETTER(Mat3, Mat3)
  TESL_DEFINE_BUILTIN_TYPE_INFO_GETTER(Mat4, Mat4)
}  